// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.dw.conference.domain;

import com.dw.conference.domain.Talk;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Talk_Roo_Configurable {
    
    declare @type: Talk: @Configurable;
    
}
